[tool.poetry]
name = "tlaloc-commons"
version = "0.1.0"
description = "A module for building API"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
